@url = http://localhost:3000

@id = 636f8a01f291c50b089b81e9
####
# @name all_stocks_details
GET {{url}}/stock_details

####
# @name stocks_details_by_id
GET {{url}}/stock_details/{{id}}

####
# @name add_stocks_details
POST {{url}}/stock_details
Content-Type: application/json

{
    "stockDetail":
    {
        "amount": "300",
        "quantity": 10,
        "stockId": "6371ff335a667020c2f77fc0",
        "transactionDate": "2022-11-11",
        "transactionType": "buy"
    }
}

###

# @name delete_stock_detail
DELETE  {{url}}/stock_details/{{id}}

###
# @name get_profit
GET {{url}}/stock_details/profit

###
# @name get_stock_profit
GET {{url}}/stock_details/stock_profit/